name: Deploy Slash Commands

# Manual workflow to run `node deploy-commands.js` in CI using repository secrets.
# Secrets required (set these in the repo Settings > Secrets):
# - CLIENT_ID
# - GUILD_ID
# - BOT_TOKEN
# Optional secrets used by other commands (include if needed): OWNER_ID, MINI_API, PIRATE_WEATHER_API_KEY, POKEMON_API_KEY

on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy commands to Discord
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create config.json from secrets
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
          MINI_API: ${{ secrets.MINI_API }}
          PIRATE_WEATHER_API_KEY: ${{ secrets.PIRATE_WEATHER_API_KEY }}
          POKEMON_API_KEY: ${{ secrets.POKEMON_API_KEY }}
        run: |
          echo 'Writing config.json (from secrets)'
          cat > config.json <<'JSON'
          {
            "clientId": "${CLIENT_ID}",
            "guildId": "${GUILD_ID}",
            "token": "${BOT_TOKEN}",
            "ownerId": "${OWNER_ID}",
            "miniAPI": "${MINI_API}",
            "pirateWeatherApiKey": "${PIRATE_WEATHER_API_KEY}",
            "pokemonApiKey": "${POKEMON_API_KEY}"
          }
          JSON

      - name: Deploy commands
        run: |
          echo 'Running deploy-commands.js'
          node deploy-commands.js
